# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
User.create!(name: "Superman")
User.create!(name: "Batman")
User.create!(name: "Green Arrow")
User.create!(name: "Spider-Man")
User.create!(name: "Spider-Girl")
User.create!(name: "Iron Man")
User.create!(name: "Hal Jordan")
User.create!(name: "Rorschach")
User.create!(name: "Nite Owl")
User.create!(name: "Wonder Woman")
User.create!(name: "Mr. Fantastic")
User.create!(name: "Invisible Wom")
User.create!(name: "Thing")
User.create!(name: "Human Torch")
User.create!(name: "Roy Harper")
User.create!(name: "Bart Allen")
User.create!(name: "Tim Drake")
User.create!(name: "Wonder Girl")
User.create!(name: "Beast Boy")
User.create!(name: "Cyborg")
User.create!(name: "Superboy")
User.create!(name: "Barbara Gordo")
User.create!(name: "Black Lightni")
User.create!(name: "Billy Batson")
User.create!(name: "Aquaman")
User.create!(name: "Thor")
User.create!(name: "Miss Arrowett")
User.create!(name: "Wolverine")
User.create!(name: "Hawkeye")
User.create!(name: "Jay Garrick")
User.create!(name: "Alan Scott")
User.create!(name: "Dr. Manhattan")
User.create!(name: "Deadpool")
User.create!(name: "Storm")
User.create!(name: "Professor X")
User.create!(name: "Martian Manhu")
User.create!(name: "Menos")
User.create!(name: "Mas")
User.create!(name: "Krypto")
User.create!(name: "Daredevil")
User.create!(name: "Ted Kord")
User.create!(name: "Kyle Rayner")
User.create!(name: "Rose Wilson")
User.create!(name: "Raven")
User.create!(name: "Starfire")
User.create!(name: "The Comedian")
User.create!(name: "Jericho")
User.create!(name: "Mia Dearden")
User.create!(name: "Dick Grayson")
User.create!(name: "Barry Allen")

Company.create!(name:"Apple Inc.")
Company.create!(name:"Orange Inc.")
Company.create!(name:"Pear LLC.")
Company.create!(name:"Grape LLP.")
Company.create!(name:"Melon Inc.")

Employment.create!(user_id: "1", company_id: "1", manager: true, staff: false)
Employment.create!(user_id: "2", company_id: "1", manager: false, staff: true)
Employment.create!(user_id: "3", company_id: "1", manager: false, staff: true)
Employment.create!(user_id: "4", company_id: "1", manager: false, staff: true)
Employment.create!(user_id: "5", company_id: "1", manager: false, staff: true)
Employment.create!(user_id: "6", company_id: "1", manager: false, staff: true)
Employment.create!(user_id: "7", company_id: "1", manager: false, staff: true)
Employment.create!(user_id: "8", company_id: "1", manager: false, staff: true)
Employment.create!(user_id: "9", company_id: "1", manager: false, staff: true)
Employment.create!(user_id: "10", company_id: "1", manager: false, staff: true)

Employment.create!(user_id: "11", company_id: "2", manager: true, staff: false)
Employment.create!(user_id: "12", company_id: "2", manager: false, staff: true)
Employment.create!(user_id: "13", company_id: "2", manager: false, staff: true)
Employment.create!(user_id: "14", company_id: "2", manager: false, staff: true)
Employment.create!(user_id: "15", company_id: "2", manager: false, staff: true)
Employment.create!(user_id: "16", company_id: "2", manager: false, staff: true)
Employment.create!(user_id: "17", company_id: "2", manager: false, staff: true)
Employment.create!(user_id: "18", company_id: "2", manager: false, staff: true)
Employment.create!(user_id: "19", company_id: "2", manager: false, staff: true)
Employment.create!(user_id: "20", company_id: "2", manager: false, staff: true)

Employment.create!(user_id: "21", company_id: "3", manager: true, staff: false)
Employment.create!(user_id: "22", company_id: "3", manager: false, staff: true)
Employment.create!(user_id: "23", company_id: "3", manager: false, staff: true)
Employment.create!(user_id: "24", company_id: "3", manager: false, staff: true)
Employment.create!(user_id: "25", company_id: "3", manager: false, staff: true)
Employment.create!(user_id: "26", company_id: "3", manager: false, staff: true)
Employment.create!(user_id: "27", company_id: "3", manager: false, staff: true)
Employment.create!(user_id: "28", company_id: "3", manager: false, staff: true)
Employment.create!(user_id: "29", company_id: "3", manager: false, staff: true)
Employment.create!(user_id: "30", company_id: "3", manager: false, staff: true)

Employment.create!(user_id: "31", company_id: "4", manager: true, staff: false)
Employment.create!(user_id: "32", company_id: "4", manager: false, staff: true)
Employment.create!(user_id: "33", company_id: "4", manager: false, staff: true)
Employment.create!(user_id: "34", company_id: "4", manager: false, staff: true)
Employment.create!(user_id: "35", company_id: "4", manager: false, staff: true)
Employment.create!(user_id: "36", company_id: "4", manager: false, staff: true)
Employment.create!(user_id: "37", company_id: "4", manager: false, staff: true)
Employment.create!(user_id: "38", company_id: "4", manager: false, staff: true)
Employment.create!(user_id: "39", company_id: "4", manager: false, staff: true)
Employment.create!(user_id: "40", company_id: "4", manager: false, staff: true)

Employment.create!(user_id: "41", company_id: "5", manager: true, staff: false)
Employment.create!(user_id: "42", company_id: "5", manager: false, staff: true)
Employment.create!(user_id: "43", company_id: "5", manager: false, staff: true)
Employment.create!(user_id: "44", company_id: "5", manager: false, staff: true)
Employment.create!(user_id: "45", company_id: "5", manager: false, staff: true)
Employment.create!(user_id: "46", company_id: "5", manager: false, staff: true)
Employment.create!(user_id: "47", company_id: "5", manager: false, staff: true)
Employment.create!(user_id: "48", company_id: "5", manager: false, staff: true)
Employment.create!(user_id: "49", company_id: "5", manager: false, staff: true)
Employment.create!(user_id: "50", company_id: "5", manager: false, staff: true)
